---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: prometheus-volume
# spec:
#   storageClassName: local
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/leonardo/Projetos/kubernetes-examples/Prometheus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykube-deployment
  labels:
    app: mykube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mykube-pod
  template:
    metadata:
      labels:
        app: mykube-pod
    spec:
      containers:
        - name: mykube-pod
          image: mykube
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pod
  template:
    metadata:
      labels:
        app: prometheus-pod
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-volume
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-volume
          hostPath:
            path: /prometheus
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mykube-service
spec:
  type: NodePort
  selector:
    app: mykube-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30180
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus-pod
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30190
